[versions]
kotlin = "1.9.24"
kotlin-runtime = "1.9.24"
agp = "8.7.3"
publish = "0.34.0"

junit = "4.13.2"

[libraries]
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version = "1.6.4" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-runtime" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
